name: CuteKits
version: '${project.version}'
main: nebcutekits.cutekits.CuteKits
api-version: '1.21'
author: nebproductions
description: A specialised kit plugin made by clickednebula3 "Nebby" for nebneb.
website: http://nebneb.ddns.net/devlog
commands:
  ckits:
    description: Main command for CuteKits
    aliases: [cutekits, ck, k]
    usage: /ckits {load [default <name>|personal <num>|global <player> <num>] || save [default <name> <overridenum>|current <overridenum>|global <player> <num> <overridenum>] || move <num> <overridenum> || delete <num> || shout <num> || items}
    permission: cutekits.ckits
  ckadmin:
    description: Admin command for CuteKits
    aliases: [cutekitsadmin, ckitsadmin]
    usage: /ckadmin {More stuff I forgot to put here}
    permission: cutekits.admin
  ck1:
    description: Quick loads your first saved kit.
    aliases: [k1]
    usage: /k1
    permission: cutekits.ckits
  ck2:
    description: Quick loads your second saved kit.
    aliases: [k2]
    usage: /k2
    permission: cutekits.ckits