data:
  maxPersonalKitCount: 5
  rankPersonalKitCount: 5
  v: 2

defaultCollections:
  - collectionName: fresh
    kits:
      - kitName: freshiron
        creation_world: worldio
        requiresBuildBreak: false
        inventory:
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: IRON_SWORD
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: IRON_BOOTS
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: IRON_LEGGINGS
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: IRON_CHESTPLATE
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: IRON_HELMET
          - null

playerCollections:
  - ownerUUID: c1b99d0e-b001-499f-a331-8e6fc12ea6cd
    collectionName: CyberBlades
    kits:
      - kitName: A Cute Kit
        creation_world: worldio
        requiresBuildBreak: false
        inventory:
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: IRON_SWORD
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - null
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: IRON_BOOTS
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: IRON_LEGGINGS
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: IRON_CHESTPLATE
          - ==: org.bukkit.inventory.ItemStack
            v: 3337
            type: IRON_HELMET
          - null